### ISSUE TITLE
Request error 400 in recognition

### ISSUE THREAD

**Issue by 99Arrzel** [exadel-inc/compreface-javascript-sdk#42]
Request failes with 400 error even when data is correct

> const url = "http://localhost";
> const port = 8000;
> const compreFace = new CompreFace(url, port);
> const recognitionService = compreFace.initFaceRecognitionService(api_key); 
> const reconocer = await recognitionService.recognize(url, options);

**Expected behavior**
Perform Image recognition

**Additional context**
Trying to use the recognition api returns error 400
data: { message: 'Something went wrong, please try again', code: 0 }

**Comment by 99Arrzel** [comment]
My error, I thought it could receive an URL but instead it works with a local path.

**Comment by pospielov** [comment]
It should work with URL. But from your code I see that you send "http://localhost/" as an image URL instead of the real image URL

**Comment by 99Arrzel** [comment]
Sorry for the delay, yeah, I just put it as an example, but might be my bad since I didn't declare the port that I'm using, anyways it's working, thanks!
