### ISSUE TITLE
Is there a Webcam Recognition App for JavaScript SDK?

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [exadel-inc/compreface-javascript-sdk#46]
Hi everyone,

I have recently tested out the ```compreface_webcam_recognition_demo.py``` file and it works well in Detection as well as Recognition of saved faces.

I would like to test out the JavaScript sdk for the same application but running on a browser, the ```app.js``` in the ```webcam_demo``` works well as well but it is only able to perform face detection (I've provided the ```detection_key```)

I would like to ask, is there a similar application to the ```compreface_webcam_recognition_demo.py``` but in JavaScript where I can run the application on a web browser and I am able to detect as well as recognize the saved faces?

Thanks and regards,
Abu

**Comment by pospielov** [comment]
We didn't create such a demo, but it's easy to change the detection demo to a recognition demo.
You need to change a couple of methods and API key in `App.js` file

**Comment by abuelgasimsaadeldin** [comment]
Hi @pospielov,

I see, I actually came across the ```webcam_demo.html``` recently which performed recognition and was exactly what I was looking for. I am now trying to convert the following html file to a .js file to use in my application, unfortunately, I have yet to be successfully. I am posting my codes here and would highly appreciate any input (apologies as I'm fairly new to JS).

```
function video() {
    let video = document.getElementById("live");
    let canvas = document.getElementById("canvas");
    let canvas2 = document.getElementById("canvas2");
    let ctx = canvas.getContext('2d');
    let ctx2 = canvas2.getContext('2d');

    navigator.mediaDevices.getUserMedia({
        video: {width: 640, height: 480}
    }).then(function (stream) {
        video.srcObject = stream;

        document.addEventListener("next_frame", draw);

        const evt = new Event("next_frame", {"bubbles": true, "cancelable": false});
        document.dispatchEvent(evt);
    });

    function draw() {
        ctx.drawImage(video, 0, 0, 640, 480);
        canvas.toBlob(function (blob) {
            blob.name = "blob.jpeg"
            let fd = new FormData();
            fd.append('file', blob, "blob.jpeg");

            fetch('http://localhost:8000/api/v1/recognition/recognize',
                {
                    method: "POST",
                    headers: {
                        "x-api-key": "5a5daa59-e85d-4f16-b92b-3f192c4bdcd3"
                    },
                    body: fd
                }
            ).then(r => r.json()).then(
                function (data) {
                    const evt = new Event("next_frame", {"bubbles": true, "cancelable": false});
                    document.dispatchEvent(evt);
                    ctx2.clearRect(0, 0, 640, 480);
                    ctx2.drawImage(video, 0, 0, 640, 480);
                    if (!data.result) {
                        return;
                    }
                    let box = data.result[0].box;
                    let similarity = data.result[0].subjects[0].similarity
                    let name = data.result[0].subjects[0].subject;
                    if (similarity > 0.95)
                        name = data.result[0].subjects[0].subject;
                    else
                        name = "guest";
                    ctx2.lineWidth = 3;
                    ctx2.strokeStyle = 'green';
                    ctx2.strokeRect(box.x_min, box.y_min, box.x_max - box.x_min, box.y_max - box.y_min);
                    ctx2.font = '24px serif';
                    ctx2.strokeText(name, box.x_min, box.y_min - 20);
                    console.log("Welcome: ", name)
                });
        }, 'image/jpeg', 0.95);
    }
}
window.onload = video;
{
<head>
    <title>test</title>
</head>
<video id="live" width="640" height="480" autoplay style="display:none;"></video>
<canvas width="640" id="canvas" height="480" style="display:none;"></canvas>
<canvas width="640" id="canvas2" height="480"></canvas>
}

Best regards,
Abu
```

**Comment by pospielov** [comment]
You can just open webcam_demo.html in a browser, it should work as is. 
Just don't forget to change api-key

**Comment by abuelgasimsaadeldin** [comment]
Hi @pospielov,

sorry for the late response, I have been away for awhile but I am back now, I was trying to find "webcam_demo.html" in this entire repository but was unable to locate it. I am not sure exactly where I have gotten a hold of it the last time, but your help in locating it would be highly appreciated.

Best,
Abu

**Comment by pospielov** [comment]
Sorry, I didn't mention that it's located in the main repository:
https://github.com/exadel-inc/CompreFace/blob/master/docs/demos/webcam_demo.html
